createDriver:
  events:
    - http:
        path: /
        method: POST
        cors: true

updateDriver:
  events:
    - http:
        path: /{id}
        method: POST
        cors: true

deleteDriver:
  events:
    - http:
        path: /{id}
        method: DELETE
        cors: true

listDrivers:
  events:
    - http:
        path: /
        method: GET
        cors: true

getDriver:
  events:
    - http:
        path: /{id}
        method: GET
        cors: true

getDriverDepartures:
  events:
    - http:
        path: /{id}/departures
        method: GET
        cors: true
