createCar:
  events:
    - http:
        path: /
        method: POST
        cors: true

updateCar:
  events:
    - http:
        path: /{id}
        method: POST
        cors: true

deleteCar:
  events:
    - http:
        path: /{id}
        method: DELETE
        cors: true

listCars:
  events:
    - http:
        path: /
        method: GET
        cors: true

getCar:
  events:
    - http:
        path: /{id}
        method: GET
        cors: true
