createList:
  events:
    - http:
        path: /
        method: POST
        cors: true

deleteList:
  events:
    - http:
        path: /{id}
        method: DELETE
        cors: true

getLists:
  events:
    - http:
        path: /{id}
        method: GET
        cors: true
