createList:
  events:
    - http:
        path: /
        method: POST
        cors: true

deleteList:
  events:
    - http:
        path: /{id}
        method: DELETE
        cors: true

getLists:
  events:
    - http:
        path: /
        method: GET
        cors: true

addToList:
  events:
    - http:
        path: /{id}/add
        method: POST
        cors: true

removeFromList:
  events:
    - http:
        path: /{id}/remove
        method: POST
        cors: true
